services:
  mysql:
    image: mysql:8.0
    container_name: paymentpoc-nodejs-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: payment_poc
      MYSQL_USER: payment_user
      MYSQL_PASSWORD: payment_pass
      TZ: Asia/Taipei
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7-alpine
    container_name: paymentpoc-nodejs-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:

